config/routes.rb
DNSAdminGui::Application.routes.draw do
  get "home/index"
  
  root :to => "home#index"

  
  resources :dns_admins
  resources :users
  resources :commits
  resources :zone_files do
      resources :records
  end

  match "zone_files/:id/commit" => "zone_files#commit"
  match "zone_files/:id/changes" => "zone_files#changes"
  match "zone_files/:id/records/reorder" => "zone_files#reorder"
  match "record_admins" => "zone_files#record_admins"
  match "slave_addresses" => "zone_files#slave_addresses"
    
  match "commits/:id/diff_data" => "commits#diff_data"
  

end

app/models/commit.rb
class Commit < ActiveRecord::Base
    belongs_to :user
    belongs_to :zone_file
    
    def get_created
        Time.parse(self.created.to_s).strftime("%Y-%m-%d %H:%M:%S")
    end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController

    before_filter :init, :only => [:edit, :show]

    def index
        @commits = Commit.all(:order => "commits.created DESC")

        respond_to do |format|
            format.html
        end
    end

    def edit
    end

    def update
    end
    
    def show
    end

    def create
    end

    def new
    end

    def destroy
    end

    def diff_data
        @commit = Commit.find(params[:id])
        response = ""
        
        if not @commit.diff_data.nil?
            response = JSON.parse(@commit.diff_data)
        end
        
        respond_to do |format|
            format.json {render :json => response}
            format.html {render :json => response}
        end
    end
    
    protected

    def init
        @commit = Commit.find(params[:id])
        @title = @commit.action
    end
end

app/views/commits/index.html.erb
<h1>Commit history</h1>
 
<% if admin? %>
	 
	<div class="ui-wrapper cb"> 
		<table class="ui-list ui-round ui-shadow">
		    <tr class="ui-header">
		    		<th>Zone</th>
				    <th>Action</th>
				    <th>Result</th>
				    <th>Response</th>
				    <th>Commited on</th>
				    <th>Commited by</th>
				    <th></th>
			    </tr>
	 
				<% @commits.each do |commit| %>
				  <tr>
				    <td class="monospace"><b><a href="<%= edit_zone_file_path commit.zone_file %>"><%= commit.zone_file.origin %></a></b></td>
				    <td class="monospace"><%= commit.action %></td>
				    <td class="monospace status-<%= (commit.result == 1) ? "success" : "failure" %>"><%= (commit.result == 1) ? "Success" : "Failure" %></td>
				    <td class="monospace"><%= commit.response %></td>
				    <td class="monospace"><%= commit.get_created %></td>
				    <td class="monospace"><%= "#{commit.user.username} (ID: #{commit.user.id})" %></td>
				    <td class="ui-action ui-show"><%= link_to 'show', commit_path(commit) %></td>
				  </tr>
				<% end %>
		</table>
	</div>
<% else %>
	<h2 class="unauthorized">You are not authorized to view this page.</h2>
<% end %>

app/views/commits/show.html.erb
<script type="text/javascript">
	$(document).ready(function() {
	    var zoneId = $('#ZoneId').val();
	    var commitId = $('#CommitId').val();
	    
	    loadCommitChanges(zoneId, url.out('commits/' + commitId + '/diff_data'));
	});
</script>

<h1>Commit details: <%= raw "<i>#{@commit.zone_file.origin}</i> from #{@commit.get_created} by #{@commit.user.username} (ID: #{@commit.user.id})" %></h1>

<%= link_to 'Back', commits_path, :id => "EditBack" %>
 
<% if defined? notice and !notice.nil? %> 
<div class="notice <%= (defined? notice_class) ? notice_class : "info" %>"><%= notice %></div>
<% end %>
 
<div id="EditCommit" class="ui-round ui-shadow">

	<div id="CommitAction">
		<h3>Commit action:</h3>
		<p><%= @commit.action %></p>
	</div>
	
	<div id="CommitResult">
		<h3>Commit result:</h3>
		<p><%= @commit.response %></p>
	</div>
	
	<input type="hidden" id="ZoneId" value="<%= @commit.zone_file.id %>" />
	<input type="hidden" id="CommitId" value="<%= @commit.id %>" />
	
	<div id="CommitChangesLoadingBar" class="loading-bar"></div>
	<div id="CommitChanges"></div>
</div>