config/routes.rb
DNSAdminGui::Application.routes.draw do
  get "home/index"
  
  root :to => "home#index"

  
  resources :dns_admins
  resources :users
  resources :commits
  resources :zone_files do
      resources :records
  end

  match "zone_files/:id/commit" => "zone_files#commit"
  match "zone_files/:id/changes" => "zone_files#changes"
  match "zone_files/:id/records/reorder" => "zone_files#reorder"
  match "record_admins" => "zone_files#record_admins"
  match "slave_addresses" => "zone_files#slave_addresses"
    
  match "commits/:id/diff_data" => "commits#diff_data"
  

end

app/models/dns_admin.rb
class DnsAdmin < ActiveRecord::Base

    $command = "curl -k -s --connect-timeout 5 -X %s --user %s:%s %s %s/%s"
        
    has_and_belongs_to_many :zone_files
    
    validates :name,  :presence => true
    validates :address, :presence => true
    validates :user, :presence => true
    validates :password, :presence => true
    
    def get_save_curl(zonefile, reload = true)
        return nil if self.id.nil?
        
        protocol = self.use_ssl? ? "https://" : "http://";
        method = "PUT"
        route = "save_zone"
        
        data_zonefile = " -d zonefile=#{zonefile} "
        data_reload = reload ? " -d reload=true " : " "
        data = "#{data_zonefile} #{data_reload}"
        
        address = "#{protocol}#{self.address}"
        
        $command % [method, self.user, self.password, data, address, route]
    end
    
    def get_delete_curl(zonefile)
        return nil if self.id.nil?
        
        protocol = self.use_ssl? ? "https://" : "http://";
        method = "DELETE"
        route = "delete_zone"
        
        data = " -d zonefile=#{zonefile} "
        
        address = "#{protocol}#{self.address}"
        
        $command % [method, self.user, self.password, data, address, route]
    end
    
    def use_ssl?
        (self.use_ssl == 1)
    end
end

app/controllers/dns_admins_controller.rb
class DnsAdminsController < ApplicationController

    before_filter :init, :only => [:edit, :update]

    def index        
        @dnsadmins = DnsAdmin.all(:order => "dns_admins.name ASC")

        respond_to do |format|
            format.html
        end
    end

    def edit
        return if not self.check
    end

    def update
        return if not self.check
        
        respond_to do |format|
            if @dnsadmin.update_attributes(params[:dns_admin])
                format.html  { redirect_to(edit_dns_admin_path(@dnsadmin),
                    :notice => 'DNS admin was successfully updated.') }
            else
                format.html  { render :action => "edit" }
            end
        end
    end

    def create
        return if not self.check
        
        @dnsadmin = DnsAdmin.new(params[:dns_admin])

        respond_to do |format|
            if @dnsadmin.save
                format.html  { redirect_to(edit_dns_admin_path(@dnsadmin),
                    :notice => 'DNS admin was successfully created.') }
                #          format.json  { render :json => @dnsadmin,
                #                        :status => :created, :location => @dnsadmin }
            else
                format.html  { render :action => "new" }
            end
        end
    end

    def new
        return if not self.check
        
        @dnsadmin = DnsAdmin.new
        @dnsadmin.use_ssl = 1

        respond_to do |format|
            format.html
        end
    end

    def destroy
        return if not self.check
        
        @dnsadmin = DnsAdmin.find(params[:id])
        @dnsadmin.destroy

        respond_to do |format|
            format.html { redirect_to dns_admins_url }
        end
    end

    protected

    def init
        @dnsadmin = DnsAdmin.find(params[:id])
        @title = @dnsadmin.name
    end
    
    protected
    
    def check
        if not view_context.admin?
            render :nothing => true
            return false
        end
        true
    end
end

app/views/dns_admins/_form.html.erb
<%= form_for(@dnsadmin, :html => {:autocomplete => "off"}) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <div class="cb"></div>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
    <div class="cb"></div>
  </div>
  <div class="field">
    <%= f.label :user %>
    <%= f.text_field :user %>
    <div class="cb"></div>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
    <div class="cb"></div>
  </div>
  <div class="field">
    <%= f.label :use_ssl, "Use SSL" %>
    <%= f.check_box :use_ssl %>
    <div class="cb"></div>
  </div>
  <div class="actions">
    <%= f.submit "Update DNS admin", :class => "save-admin" %>
  </div>
<% end %>

app/views/dns_admins/edit.html.erb
<h1>Editing DNS admin "<%= @dnsadmin.name %>"</h1>
 
<%= link_to 'Back', dns_admins_path, :id => "EditBack" %>
 
<% if defined? notice and !notice.nil? %> 
<div class="notice <%= (defined? notice_class) ? notice_class : "info" %>"><%= notice %></div>
<% end %>
 
<div id="EditAdmin" class="ui-round ui-shadow">
	<%= render 'form' %>
</div>

app/views/dns_admins/index.html.erb
<h1>DNS masters</h1>

<% if admin? %>
 
	<%= link_to "Add new", new_dns_admin_path, :id => "NewAdmin" %>
	 
	<div class="ui-wrapper cb"> 
		<table class="ui-list ui-round ui-shadow">
		    <tr class="ui-header">
				    <th>Name</th>
				    <th>Address</th>
				    <th></th>
				    <th></th>
			    </tr>
	 
				<% @dnsadmins.each do |adm| %>
				  <tr>
				    <td class="monospace"><%= adm.name %></td>
				    <td class="monospace"><%= adm.address %></td>
				    <td class="ui-action ui-edit"><%= link_to 'edit', edit_dns_admin_path(adm) %></td>
				    <td class="ui-action ui-delete"><%= link_to 'delete', adm, :confirm => 'Are you sure?',
				                                     :method => :delete %></td>
				  </tr>
				<% end %>
		</table>
	</div>
<% else %>
	<h2 class="unauthorized">You are not authorized to view this page.</h2>
<% end %>

app/views/dns_admins/new.html.erb
<h1>New DNS admin</h1>
 
<%= link_to 'Back', dns_admins_path, :id => "EditBack" %>
 
<% if defined? notice and !notice.nil? %> 
<div class="notice <%= (defined? notice_class) ? notice_class : "info" %>"><%= notice %></div>
<% end %>
 
<div id="EditAdmin" class="ui-round ui-shadow">
	<%= render 'form' %>
</div>