config/routes.rb
DNSAdminGui::Application.routes.draw do
  get "home/index"
  
  root :to => "home#index"

  
  resources :dns_admins
  resources :users
  resources :commits
  resources :zone_files do
      resources :records
  end

  match "zone_files/:id/commit" => "zone_files#commit"
  match "zone_files/:id/changes" => "zone_files#changes"
  match "zone_files/:id/records/reorder" => "zone_files#reorder"
  match "record_admins" => "zone_files#record_admins"
  match "slave_addresses" => "zone_files#slave_addresses"
    
  match "commits/:id/diff_data" => "commits#diff_data"
  

end

app/models/zone_file.rb
class ZoneFile < ActiveRecord::Base  
    has_and_belongs_to_many :dns_admins
    has_and_belongs_to_many :users, :order => "username ASC"
    belongs_to :user
    has_many :commits
    
    validates :origin,  :presence => true
    validates :ttl, :presence => true
    validates :address, :presence => true
    validates :nameserver, :presence => true
    validates :email, :presence => true
    validates :serial_number, :presence => true
    validates :slave_refresh, :presence => true
    validates :slave_retry, :presence => true
    validates :slave_expiration, :presence => true
    validates :max_cache, :presence => true
    
    def self.get_all       
        select('zf.*').
            from('zone_files as zf').
            where('zf.status = 0').
            where('zf.id = (SELECT MAX(zf2.id) FROM zone_files AS zf2 WHERE zf2.group_id = zf.group_id GROUP BY zf2.group_id)').
            order('zf.label ASC, zf.origin ASC')
    end
    
    def self.get_zones_for_user(user_id)
        self.get_all.where('EXISTS(SELECT * FROM `users_zone_files` WHERE `user_id` = ? AND `zone_file_id` = `zf`.`id`)', user_id)        
    end
    
    def self.get_current(group_id)
        select('zf.*').
            from('zone_files as zf').
            where('zf.status = 0').
            where("zf.id = (SELECT MAX(zf2.id) FROM zone_files AS zf2 WHERE zf2.group_id = #{group_id} GROUP BY zf2.group_id)").
            first    
    end
    
    def create_record(data)
        record = Record.new(data)
        record.zone_file_group_id = self.group_id
        record
    end
    
    def inc_sn(save = true)
        time = Time.new.strftime("%Y%m%d")
        sn = self.serial_number.to_s[0, time.length]
        if time == sn
            self.serial_number += 1
        else
            self.serial_number = (time + "01").to_i
        end
        self.save if save
    end
    
    def records
        get_all_records
    end
    
    def get_all_records(with_deleted = false)
        Record.get_all self.group_id, with_deleted
    end
    
    def mark_as_deleted
        self.status = 1
        self.save        
    end
    
    def get_commit_changes
        {:soa => self.get_soa_changes, :records => self.get_records_changes}
    end
    
    def get_soa_changes
        result = {:current => {}, :previous => {}}
            
        if self.dirty?
            result[:current] = JSON.parse(self.to_json)
                
            result[:current][:user] = {
                :username => self.user.username,
                :usertype => self.user.usertype, 
                :id => self.user.id
            }
            
            if not self.first?
                previous = ZoneFile.find(self.previous_id)
                result[:previous] = JSON.parse(previous.to_json)
                
                result[:previous][:user] = {
                    :username => previous.user.username,
                    :usertype => previous.user.usertype, 
                    :id => previous.user.id
                }
            end
        end
        
        result
    end
    
    def get_records_changes
        r = self.get_all_records true
        records = []
        
        r.each do |record|
            hash = JSON.parse(record.to_json)
            
            if record.dirty? and record.status == 0 and record.previous_id > 0
                previous = Record.find(record.previous_id)
                hash[:previous] = JSON.parse(previous.to_json)                    
                hash[:previous][:user] = {
                    :username => previous.user.username,
                    :usertype => previous.user.usertype, 
                    :id => previous.user.id
                }                
            end
            
            hash[:user] = {
                :username => record.user.username,
                :usertype => record.user.usertype, 
                :id => record.user.id
            }
            
            records << hash
        end
        
        records
    end
    
    def dnsa=(list)
        self.dns_admins.clear
        
        list.each { |id| 
            self.dns_admins << DnsAdmin.find(id) if DnsAdmin.exists? id
        }
    end
    
    def slaves_attr=(value, delimiter = ",")
        list = Set.new(value.split(delimiter).collect{ |item| item.strip})
        list.delete ""
         
        self.slaves = list.to_json
    end
    
    def slaves_attr(delimiter = ", ")
        self.slaves.nil? ? "" : JSON.parse(self.slaves).join(delimiter)
    end
    
    def record_admins_attr=(value, delimiter = ",")
        users = Set.new(value.split(delimiter).collect{ |user| user.strip})
        users.delete ""
        
        self.users.clear
        
        users.each do |user|
            u = User.where(:username => user).first
            self.users << u if not u.nil?
        end
    end
    
    def record_admins_attr(delimiter = ", ")
        users = self.users.all.collect { |user| user.username}
        users.join(delimiter)
    end
    
    def commit_required?        
        Record.has_dirty_record(self.group_id) or dirty?
    end
    
    def dirty!
        self.is_dirty = 1
        self
    end
    
    def commit!
        self.is_dirty = 0
        self.save
        
        self.get_all_records(true).each { |record|
            record.commit!
        }
        
        self
    end
    
    def dirty?
        self.is_dirty == 1
    end
    
    def first?
        self.previous_id == 0
    end
    
    def to_compact
        return nil if self.id().nil?
        
        records = []
            
        self.records.each { |record|
            records.push record.to_compact
        }
        
        {
            :origin => self.origin,
            :ttl => self.ttl,
            :soa => {
                :address => self.address,
                :ns => self.nameserver,
                :email => self.email,
                :serialNumber => self.serial_number,
                :slaveRefresh => self.slave_refresh,
                :slaveRetry => self.slave_retry,
                :slaveExpiration => self.slave_expiration,
                :maxCacheTime => self.max_cache
            },
            :slaves => JSON.parse(self.slaves),
            :records => records
        }
    end
    
    def get_created
        Time.parse(self.created.to_s).strftime("%Y-%m-%d %H:%M:%S")
    end
    
end

app/controllers/zone_files_controller.rb
class ZoneFilesController < ApplicationController

    before_filter :init, :only => [:edit, :update]
        
    def index
        if view_context.admin?
            @zonefiles = ZoneFile.get_all
        else
            @zonefiles = ZoneFile.get_zones_for_user(session[:user].id)
        end
        
        respond_to do |format|
            format.html
            format.json  { render :json => @zonefiles }
        end
    end

    def edit
        latest_zonefile = ZoneFile.get_current(@zonefile.group_id)
        
        if latest_zonefile.id != @zonefile.id
            redirect_to({:action => "edit", :controller => "zone_files", :id => latest_zonefile.id})
        end
    end

    def update
        return if not self.check
        #abort @zonefile.inspect
        
        params[:zone_file][:origin] = @zonefile.origin
        
        @next_zonefile = ZoneFile.new(params[:zone_file])
        @next_zonefile.previous_id = @zonefile.id
        @next_zonefile.user_id = get_user_id

        respond_to do |format|
            if @next_zonefile.save
                @next_zonefile.dirty!
                #@next_zonefile.inc_sn false
                @next_zonefile.save
                format.html  { redirect_to({:action => "edit", :controller => "zone_files", :id => @next_zonefile.id},
                    :notice => 'Zone file was successfully updated.')}
            else
                format.html  { render :action => "edit", :locals => {
                        :notice => 'Zone file cannot be saved - there are errors.', :notice_class => "error"}}
            end
        end
    end

    def create   
        return if not self.check   
        @zonefile = ZoneFile.new(params[:zone_file])
        @zonefile.user_id = get_user_id
        @dnsadmins = DnsAdmin.all

        respond_to do |format|
            if @zonefile.save
                @zonefile.group_id = @zonefile.id
                @zonefile.save
                
                format.html  { redirect_to({:action => "edit", :controller => "zone_files", :id => @zonefile.id},
                    :notice => 'Zone file was successfully created.') }
            else
                format.html  { render :action => "new" }
            end
        end
    end

    def new
        return if not self.check
        
        @zonefile = ZoneFile.new({
            :origin => "domain.",
            :ttl => "1H",
            :address => "@",
            :nameserver => "ns1",
            :email => "admin@example.com.",
            :serial_number => Time.new.strftime("%Y%m%d") + "01",
            :slave_refresh => "1D",
            :slave_retry => "2H",
            :slave_expiration => "4W",
            :max_cache => "1H"
        })

        @dnsadmins = DnsAdmin.all
        @new_record = Record.new

        respond_to do |format|
            format.html
        end
    end

    def record_admins
        users = User.search_by_term params[:term]
        
        response = []
        
        users.each do |user|
            response << {
                :id => user.username,
                :label => user.username,
                :value => user.username
            }
        end
        
        respond_to do |format|
            format.json { render :json => response }
        end
    end

    def slave_addresses
        addresses = Set.new
        term = params[:term]
        
        ZoneFile.all.each { |zf|
            addresses.merge(zf.slaves.nil? ? [] : JSON.parse(zf.slaves).collect{|a| (term.nil? or (a.length >= term.length and a[0, term.length] == term)) ? a : ""})
        }
        
        addresses.delete ""

        respond_to do |format|
            format.json { render :json => addresses }
        end
    end
        
    def destroy     
        return if not self.check
        
        @zonefile = ZoneFile.find(params[:id])
        @zonefile = ZoneFile.get_current(@zonefile.group_id)
            
        success, report = delete_zone(@zonefile)
        @zonefile.mark_as_deleted if success

        respond_to do |format|
            if success
                format.html  { redirect_to zone_files_url, :notice => report}
            else
                format.html  { redirect_to zone_files_url, :alert => report}
            end
        end
    end

    def commit
        @zonefile = ZoneFile.find(params[:id])

        # commit to masters
        success, report = save_zone(@zonefile)

        @zonefile.commit! if success
        
        respond_to do |format|
            if success
                format.html  { redirect_to edit_zone_file_path(@zonefile),
                    :notice => report}
            else
                format.html  { redirect_to edit_zone_file_path(@zonefile),
                    :alert => report}
            end
        end
    end
    
    def changes
        @zonefile = ZoneFile.find(params[:id])
        
        response = @zonefile.get_commit_changes
            
        respond_to do |format|
            format.html {render :json => response}
            format.json {render :json => response}
        end
    end

    def reorder
        zonefile = ZoneFile.find params[:id]
        
        if view_context.can_edit_records? zonefile
            i = 1;
            params[:records].each { |record_id|
                Record.find(record_id).set_order(i)
                i += 1
            }
        end

        respond_to do |format|
            format.json { head :no_content }
        end
    end

    protected

    def init
        @zonefile = ZoneFile.find(params[:id])
        @dnsadmins = DnsAdmin.all
        @new_record = Record.new
        @title = @zonefile.origin
        @title += " (#{@zonefile.label})" if !@zonefile.label.nil? and !@zonefile.label.empty?
    end
    
    protected
    
    def check
        if not view_context.admin?
            render :nothing => true
            return false
        end
        true
    end

    protected

    def save_zone(zonefile)
        
        zonefile.inc_sn
        
        commit = zonefile.commits.create({:user_id => get_user_id})
        
        zone_data = zonefile.to_compact.to_json    
        zone = CGI.escape(zone_data)
        
        commit.action = 'save_zone'
        commit.request = zone_data
        commit.diff_data = zonefile.get_commit_changes.to_json

        all_success = true
        output = ""

        zonefile.dns_admins.each { |adm|
            response = `#{adm.get_save_curl(zone)}` ; success = $?.success?
            msg = get_msg response
            all_success = (all_success and (msg == "OK"))
            output += "#{adm.name} => #{msg}, "
        }

        output = output[0, output.length-2]
        output = (not output.nil? and output.length > 0) ? output : 'none'
        all_status = all_success ? 'Success' : 'Failure'
        all_msg = "Commit report: #{all_status}, details: #{(output.length > 0) ? output : 'none'}"
        
        commit.result = (all_success) ? 1 : 0
        commit.response = all_msg
        commit.save
        
        all_msg += ", <a href=\"#{commit_path(commit)}\">Full report</a>"
        
        return all_success, all_msg
    end

    protected

    def delete_zone(zonefile)
        $zone_not_found = 6
        
        commit = zonefile.commits.create({:user_id => get_user_id})
        
        all_success = true
        output = ""

        commit.action = 'delete_zone'
        
        zonefile.dns_admins.each { |adm|
            response = `#{adm.get_delete_curl(zonefile.origin)}` ; success = $?.success?
            msg = get_msg response
            err_code = get_err_code response
            all_success = (all_success and (msg == "OK" || err_code == $zone_not_found))
            output += "#{adm.name} => #{msg}, "
        }

        output = output[0, output.length-2]
        output = (not output.nil? and output.length > 0) ? output : 'none'
        all_status = all_success ? 'Success' : 'Failure'
        all_msg = "Deleting zone report: #{all_status}, details: #{output}"
        
        commit.result = (all_success) ? 1 : 0
        commit.response = all_msg
        commit.save
        
        all_msg += ", <a href=\"#{commit_path(commit)}\">Full report</a>"
        
        return all_success, all_msg
    end

    protected

    def get_msg(response)
        msg = ""

        begin
            json = JSON.parse response
            if json['errorCode'].to_s != "0"
                msg = "Error #{json["errorCode"]}: " + json['message']
            else
                msg = "OK"
            end
        rescue
            msg = "Cannot parse response (or is offline)"
        end

        msg
    end
    
    protected
    
    def get_err_code(response)
        err_code = -1
        begin
            json = JSON.parse response
            err_code = json['errorCode'].to_i
        rescue
            err_code = -1
        end
        
        err_code        
    end
end

app/views/zone_files/_form.html.erb
<% if admin? and not is_new_zone %>
	<div id="LastChanges" class="normal-element">Last changes were made by <b><a href="<%= edit_user_path @zonefile.user %>">
		<%= raw "#{@zonefile.user.username}</a></b> (ID: #{@zonefile.user.id}, type: #{get_user_type @zonefile.user.usertype}) on #{@zonefile.get_created}" %>
	</div>
<% end %>

<% css_class = (@zonefile.dirty? or is_new_zone) ? "dirty" : "" %>
<%= form_for(@zonefile, :html => {:class => "zone-file normal-element #{css_class}", :autocomplete => "off"}) do |f| %>
  
  <div class="actions">
    <%= f.submit "Save zone", :class => "save-zone" if admin? %>
  </div>
 
 <%= f.hidden_field :id %>
  <%= f.hidden_field :group_id %>
 
  <div class="field inline f-label">
    <%= f.label :label, "Label" %>
    <%= f.text_field :label %>
    <div class="cb"></div>
  </div>
 
  <div class="field inline f-origin">
    <%= f.label :origin, "$ORIGIN" %>
    <% if is_new_zone %>
    	<%= f.text_field :origin %>
    <% else %>
    	<%= f.text_field :origin, :disabled => "disabled" %>
   	<% end %>
    <div class="cb"></div>
  </div>
  <div class="field inline f-ttl">
    <%= f.label :ttl, "$TTL" %>
    <%= f.text_field :ttl %>
    <div class="cb"></div>
  </div>
    
  
  <div class="field inline f-soa">
    <%= f.label :address, "[Zone]" %>
    <%= f.text_field :address %>

	<div class="soa-text fl">SOA</div>

    <%= f.label :nameserver, "[NS]" %>
    <%= f.text_field :nameserver %>

    <%= f.label :email, "[Email]" %>
    <%= f.text_field :email %>
    <div class="cb"></div>
  </div>
  
  
  <div class="field inline f-soa-data first">
    <%= f.label :serial_number %>
    <%= f.text_field :serial_number %>
    <div class="cb"></div>
  </div>
  
  <div class="field inline f-soa-data">
    <%= f.label :slave_refresh %>
    <%= f.text_field :slave_refresh %>
    <div class="cb"></div>
  </div>
  
  <div class="field inline f-soa-data">
    <%= f.label :slave_retry %>
    <%= f.text_field :slave_retry %>
    <div class="cb"></div>
  </div>
  
  <div class="field inline f-soa-data">
    <%= f.label :slave_expiration %>
    <%= f.text_field :slave_expiration %>
    <div class="cb"></div>
  </div>
  
  <div class="field inline f-soa-data">
    <%= f.label :max_cache, "Max cache time" %>
    <%= f.text_field :max_cache %>
    <div class="cb"></div>
  </div>
  
  <div class="cb"></div>
  
  
  <div class="f-settings">
	<div class="f-settings-row">
	    <%= f.label :slaves_attr, "Slave addresses (comma delimited):", :class => "slaves" %>
	    <%= f.text_field :slaves_attr, :id => "SlaveAddresses", :class => "slaves" %>
	
	  	<div class="cb"></div>
	</div>
	
	<div class="f-settings-row">
	    <%= hidden_field_tag "zone_file[dnsa][]" %>
	    
	    <label class="dns-admins">Push to following DNS masters:</label>
	    <ul>
		  <% @dnsadmins.each do |adm| %>
		    <li data-adm-id="<%= adm.id %>">
		    	<%= check_box_tag "zone_file[dnsa][]", adm.id, (@zonefile.dns_admins.exists?(adm.id) or is_new_zone) %>
		    	<span><%= adm.name %></span>
		    </li>
		  <% end %>  
		</ul>
	    <div class="cb"></div>
    </div>
    
    <div class="f-settings-row">
	    <%= f.label :record_admins_attr, "Record admins who may edit this zone's records:", :class => "record-admin" %>
	    <%= f.text_field :record_admins_attr, :id => "RecordAdmins" %>
	</div>
  </div>
  
  	
  <div class="actions">
    <%= f.submit "Save zone", :class => "save-zone" if admin? %>
  </div>
<% end %>

<% if !is_new_zone %>
	<div class="records-header normal-element">
		<p class="r-h-name">Name</p>
		<p class="r-h-ttl">TTL</p>
		<p class="r-h-rtype">Type</p>
		<p class="r-h-data">Data</p>
		<div class="cb"></div>
	</div>
	
	<div class="cb"></div>
	
	<ul class="records normal-element">
	  	<%= render :partial => 'records', :locals => {:is_new => false} %>
	  	
	  	<% if can_edit_records? @zonefile %>
		  	<li class="f-info commit-element">
		  		<p class="info">Add new records:</p>
		  		<button id="AddRecord">Add more rows</button>
		  	</li>
			<%= render :partial => 'new_record', :locals => {:is_new => true} %>
		<% end %>
	</ul>
	
	<div id="CommitChangesLoadingBar" class="loading-bar precommit-element"></div>
	<div id="CommitChanges" class="precommit-element"></div>
	
	<div class="cb mt"></div>
	
	<% if can_edit_records? @zonefile %>
		<button class="save-all-records normal-element">Save all records</button>
	<% end %>
	<button class="precommit normal-element">Commit changes</button>
	<button class="abort-commit precommit-element">Abort commit</button>
	<%= link_to "Commit changes", zone_file_path(@zonefile) + "/commit", :class => "commit precommit-element" %>
<% end %>

app/views/zone_files/_new_record.html.erb
<li class="f-record new">
	<div class="dd-handle"></div>
    <%= render :partial => 'zone_files/record_form', :locals => {:is_new => is_new, :record => @new_record} %>
</li>

app/views/zone_files/_record_form.html.erb
<% url = zone_file_record_path(@zonefile, record, :format => :js) %>

<%= form_tag url, :method => is_new ? :post : :put, :remote => true, :class => "record-form", :autocomplete => "off" do %>

<div class="field f-r-name">
	<%= text_field_tag "record[name]", record.name %>
</div>	

<div class="field f-r-ttl">
	<%= text_field_tag "record[ttl]", record.ttl %>
</div>	

<div class="field f-r-rtype">
	<% options = (is_new) ? {:prompt => "Select record type"} : {} %>
	<%= select("record", "rtype", options_for_select(["A", "AAAA", "MX", "CNAME", "PTR", "NS", "TXT", "SRV"], record.rtype)) %>
</div>	

<div class="field f-r-data">
	<%= text_field_tag "record[data]", record.data %>
</div>

<% if can_edit_records? @zonefile %>
	<%= submit_tag "Save", :class => "save-record" %>
	<%= link_to '', [@zonefile, record], :confirm => 'Are you sure?', :format => :js, :method => :delete, :remote => true, :class => "delete-record" if !is_new %>
<% end %>

<div class="loading-bar fl"></div>

<% if admin? and not record.user.nil? %>
	<div class="last-changes"><b><a href="<%= edit_user_path record.user %>">
		<%= raw "#{record.user.username}</a></b> (ID: #{record.user.id}, type: #{get_user_type record.user.usertype}) on #{record.get_created}" %>
	</div>
<% end %>

<div class="cb"></div>
	
<% end %>

app/views/zone_files/_records.html.erb
<% @zonefile.records.each do |record| %>
    <li class="f-record commit-element <%= "dirty" if record.dirty? %> <%= ("item-#{record.id}") if !is_new %>">
      <% if !is_new %><div class="dd-handle ui-icon ui-icon-grip-dotted-vertical"></div><% end %>
      <%= render :partial => 'zone_files/record_form', :locals => {:is_new => is_new, :record => record} %>
    </li>
<% end %>

app/views/zone_files/edit.html.erb
<h1>Editing zone &quot;<%= @zonefile.origin %>&quot;</h1>
 
<%= link_to 'Back', zone_files_path, :id => "EditBack" %>
 
<% if (defined? notice and !notice.nil?) or (defined? alert and !alert.nil?) %> 
<div class="notice <%= (defined? notice_class) ? notice_class : (defined? alert and !alert.nil?) ? "error" : "info" %>"><% msg = notice || alert %><%= raw msg %></div>
<% end %>

<div id="EditZone" class="ui-round ui-shadow">
	<%= render :partial => 'form', :locals => {:is_new_zone => false} %>
</div>

app/views/zone_files/index.html.erb
<h1>Zone files</h1>

<% if (defined? notice and !notice.nil?) or (defined? alert and !alert.nil?) %> 
<div class="notice <%= (defined? notice_class) ? notice_class : (defined? alert and !alert.nil?) ? "error" : "info" %>"><% msg = notice || alert %><%= raw msg %></div>
<% end %>

<%= link_to "Add new", new_zone_file_path, :id => "NewZone" %>

<div class="ui-wrapper cb"> 
	<table class="ui-list ui-round ui-shadow">
	    <tr class="ui-header">
		    <th>Zone</th>
		    <th>Label</th>
		    <th class="ui-edit"></th>
		    <th class="ui-delete"></th>
	    </tr>
 
		<% @zonefiles.each do |zone| %>
		    <tr>
			    <td class="origin"><%= zone.origin %></td>
			    <td class="zone-label"><% if !zone.label.nil? && !zone.label.empty? %><span><%= zone.label %></span><% end %></td>
			    <td class="ui-action ui-edit"><%= link_to 'edit', edit_zone_file_path(zone) %></td>
			    <% if admin? %>
				    <td class="ui-action ui-delete"><%= link_to 'delete', zone, :confirm => 'Are you sure?',
				                                     :method => :delete %></td>
				<% else %>
					<td>&nbsp;</td>
				<% end %>
		    </tr>
		<% end %>
	</table>
</div>

app/views/zone_files/new.html.erb
<h1>New zone file</h1>
 
<%= link_to 'Back', zone_files_path, :id => "EditBack" %>
 
<% if defined? notice and !notice.nil? %> 
<div class="notice <%= (defined? notice_class) ? notice_class : "info" %>"><%= notice %></div>
<% end %>
 
<div id="EditZone" class="ui-round ui-shadow">
	<%= render :partial => 'form', :locals => {:is_new_zone => true} %>
</div>