config/routes.rb
DNSAdminGui::Application.routes.draw do
  get "home/index"
  
  root :to => "home#index"

  
  resources :dns_admins
  resources :users
  resources :commits
  resources :zone_files do
      resources :records
  end

  match "zone_files/:id/commit" => "zone_files#commit"
  match "zone_files/:id/changes" => "zone_files#changes"
  match "zone_files/:id/records/reorder" => "zone_files#reorder"
  match "record_admins" => "zone_files#record_admins"
  match "slave_addresses" => "zone_files#slave_addresses"
    
  match "commits/:id/diff_data" => "commits#diff_data"
  

end

app/controllers/application_controller.rb
class ApplicationController < AuthController
  protect_from_forgery
  
  before_filter :authenticate
  
  protected
  def authenticate
      authenticate_or_request_with_http_basic do |username, password|
          user = view_context.user_auth username, password
          
          if !user.nil?
              session[:user] = user
              return true
          end
          
          false
      end
  end
  
  def authenticated?
      defined? session[:user] and !session[:user].nil?
  end
  
  def get_user_id
      session[:user].id
  end
  
#  protected
#  def redirect_to_https(url, status = {})
#      host = DNSAdminGui::Application.config.hostname.nil? ? "" : DNSAdminGui::Application.config.hostname
#      redirect_to host + url, status
#  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def root?
        session[:user].usertype == "root"
    end
    
    def admin?
        ["admin", "root"].include?(session[:user].usertype)
    end
   
    def record_admin?
        ["admin", "root", "record_admin"].include?(session[:user].usertype)
    end
    
    def can_edit_records?(zonefile)
        admin? or zonefile.users.exists?(:id => session[:user].id)
    end
end

app/views/application/_footer.html.erb
DNS Admin v1.0 | Copyright &copy; 2012 Relbit. All rights reserved.

app/views/application/_navigation.html.erb
<div class="menu">
	<ul>
		<li><a href="<%= zone_files_path %>" target="_self" >Zones</a>
			<ul>
				<li><a href="<%= zone_files_path %>" target="_self">Zones</a></li>
			</ul>
		</li>
		<% if admin? %>
			<li><a href="<%= dns_admins_path %>" target="_self" >DNS Masters</a>
				<ul>
					<li><a href="<%= dns_admins_path %>" target="_self">DNS Masters</a></li>
				</ul>
			</li>
			<li><a href="<%= commits_path %>" target="_self" >Commit history</a>
				<ul>
					<li><a href="<%= commits_path %>" target="_self">Commit history</a></li>
				</ul>
			</li>
		<% end %>
		<% if root? %>
			<li><a href="<%= users_path %>" target="_self" >Users</a>
				<ul>
					<li><a href="<%= users_path %>" target="_self">Users</a></li>
				</ul>
			</li>
		<% end %>
	</ul>
</div>